# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='profilepics/%Y/%m/%d/')),
            ],
        ),
    ]
